FROM registry.access.redhat.com/ubi10/ubi:latest as builder

RUN uname -m && \
    dnf install -y --setopt=install_weak_deps=False \
        zlib \
        openssl-devel \
        git \
        gcc && \
    dnf clean all

ENV PATH="/root/.cargo/bin:${PATH}"

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain 1.95.0

RUN git clone https://github.com/guacsec/trustify-scale-testing --depth 1 && \
    cd trustify-scale-testing && \
    cargo build --release --bin loadtest

FROM registry.access.redhat.com/ubi10/ubi-minimal:latest

RUN microdnf install -y --setopt=install_weak_deps=0 \
        openssl && \
    microdnf clean all

COPY --from=builder /trustify-scale-testing/target/release/loadtest /usr/local/bin/loadtest
COPY scenarios/ /usr/local/share/scenarios

ENTRYPOINT ["/usr/local/bin/loadtest"]
